services:
  # git-cloner:
  #   build:
  #     context: .
  #     dockerfile: git-cloner.Dockerfile
  #   command: sh -c "git clone https://zach-schrag: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@github.com/zach-schrag/booth-assignment.git /app && ls -l /app"
  #   volumes:
  #     - ./app:/app
  #   restart: "no"

# docker run --rm -v ${PWD}/app:/app alpine/git sh -c "git clone https://zach-schrag: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@github.com/zach-schrag/booth-assignment.git /app && ls -l /app"

  client:
    build: ./src/client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      # - git-cloner
      - server

  server:
    build: ./src/server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    # depends_on:
    #   - git-cloner
